
skip_branch_with_pr: true

environment:
  python_stack: python 3.12
  PYTHON_VERSION: 3.12.6

  matrix:
    # - job_name: Build Python for Linux
    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu

    - job_name: Build Python for Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

matrix:
  fast_finish: true

stack: $python_stack

for:
  # ======================================
  #      Build Python for Linux
  # ======================================

  - matrix:
      only:
        - job_name: Build Python for Linux

    install:
      - echo install

    build_script:
      - sh: |
          echo build

  # ======================================
  #      Build Python for Windows
  # ======================================

  - matrix:
      only:
        - job_name: Build Python for Windows

    install:
      - C:\Python312\python --version

    build_script:
      - cd windows
      - curl -OL https://www.python.org/ftp/python/3.12.5/python-3.12.5-amd64.exe
      - start /wait python-3.12.5-amd64.exe /uninstall /quiet

      - curl -OL https://www.python.org/ftp/python/%PYTHON_VERSION%/python-%PYTHON_VERSION%-amd64.exe
      - start /wait python-%PYTHON_VERSION%-amd64.exe /quiet
      - dir C:\python312-dist
      - C:\python312-dist\python -m compileall -b C:\python312-dist\Lib
      - 7z a -xr@exclude.txt python-windows-for-dart-%PYTHON_VERSION%.zip C:\python312-dist\*

    test: off

    artifacts:
      - path: windows\python-windows-for-dart-*.zip

    # deploy:
    #   provider: GitHub
    #   auth_token: $(GITHUB_TOKEN)
    #   release: $(APPVEYOR_REPO_TAG_NAME)
    #   artifact: flet_windows
    #   on:
    #     APPVEYOR_REPO_TAG: true