
skip_branch_with_pr: true

environment:
  python_stack: python 3.12
  PYTHON_VERSION: 3.12.6

  matrix:
    # - job_name: Build Python for Linux
    #   APPVEYOR_BUILD_WORKER_IMAGE: ubuntu

    - job_name: Build Python for Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

matrix:
  fast_finish: true

stack: $python_stack

for:
  # ======================================
  #      Build Python for Linux
  # ======================================

  - matrix:
      only:
        - job_name: Build Python for Linux

    install:
      - echo install

    build_script:
      - sh: |
          echo build

  # ======================================
  #      Build Python for Windows
  # ======================================

  - matrix:
      only:
        - job_name: Build Python for Windows

    build_script:
      - cd windows
      - curl -OL https://www.python.org/ftp/python/%PYTHON_VERSION%/python-%PYTHON_VERSION%-amd64.exe
      - start /wait python-%PYTHON_VERSION%-amd64.exe /uninstall /quiet
      - start /wait python-%PYTHON_VERSION%-amd64.exe /quiet
      - dir C:\python312-dist
      - cd C:\python312-dist
      - 7z a python-windows-for-dart-%PYTHON_VERSION%.zip *

    test: off

    # artifacts:
    #   - path: client\build\windows\x64\runner\flet-windows.zip
    #   - path: sdk\python\packages\flet-desktop\dist\*.whl

    # deploy:
    #   provider: GitHub
    #   auth_token: $(GITHUB_TOKEN)
    #   release: $(APPVEYOR_REPO_TAG_NAME)
    #   artifact: flet_windows
    #   on:
    #     APPVEYOR_REPO_TAG: true